export const LOGIN_REQUEST_START = 'LOGIN_REQUEST_START';
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
export const LOGIN_REQUEST_CLEAR = 'LOGIN_REQUEST_CLEAR';
export const LOGIN_REQUEST_ERROR = 'LOGIN_REQUEST_ERROR';

